version: '3.8'

services:
  postgres:
    container_name: mysms
    image: postgres:latest
    environment:
      - POSTGRES_DB=mysms
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_sms_network

volumes:
  postgres_data:

networks:
  my_sms_network:
